name: colorgram
version: 2.0.0
description: Colorgram is a lightweight tool that allows you to extract prominent colors from image. This is a Dart port of the original Colorgram.js library.
homepage: https://github.com/fisherman-23/colorgram-dart/
repository: https://github.com/fisherman-23/colorgram-dart/

environment:
  sdk: '>=2.18.4 <3.0.0'
  flutter: ">=3.13.0"

# dependencies:
#   path: ^1.8.0

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.3
